apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  labels:
    k8s-app: prometheus-operator
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    k8s-app: prometheus-operator
